services:
  backend:
    build: .
    ports:
      - 3333:3333
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    command: ["./command.sh"]
  
  db:
    image: postgres:15
    container_name: edutrack_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: edutrack_db
    volumes:
      - pgdata:/var/lib/postgres/data
    ports:
      - 5433:5432

volumes:
  pgdata:
